# This file configures the deployment of the Guidance Counseling App on Render.

services:
  # --------------------- #
  #  Backend Web Service  #
  # --------------------- #
  - type: web
    name: guidance-counseling-api
    rootDir: server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      # NOTE: You will need to manually set CLIENT_URL, MONGO_URI, and JWT_SECRET
      # in the Render dashboard for this API service after it's created.
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false

  # ---------------------- #
  #  Frontend Static Site  #
  # ---------------------- #
  - type: static_site
    name: guidance-counseling-client
    rootDir: client
    env: static
    plan: free
    buildCommand: npm install && npm run build
    publishDir: ./dist
    envVars:
      # NOTE: You will need to manually set VITE_API_URL in the Render dashboard
      # for this client service after it's created.
      - key: VITE_API_URL
        value: "" # This will be overridden by the value you set in the dashboard.
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
